baseurl = "/"
publishDir = "docs"
languageCode = "en-us"
title = "Delven Documentation"
#theme = "hugo-material-docs"
theme = "hugo-theme-learn"
metadataformat = "yaml"
pluralizeListTitles = false
canonifyurls = true
search = true
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/gregbugaj/delven-docs/tree/master/content/"
  description = "Documentation for Delven Data Extract Engine"
  author = "Greg Bugaj"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false