version: '3.3'

services:

   delven_ui:
    container_name: explorer-ui
    build:  ../../explorer-ui
    restart: always
    ports:
      - 8088:8088
    networks:
      - delvnet


  # delven_ui:
  #   container_name: explorer-ui
  #   image:  delven/explorer-ui:1.0
  #   restart: always
  #   ports:
  #     - 8088:8088
  #   networks:
  #     - delvnet

networks:
  delvnet:
