name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

defaults:
  run:
    working-directory: .

jobs:
#  test_transpiler:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./transpiler
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-node@v2
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test

  build_transpiler:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transpiler
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build --if-present

  build_explorer_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./explorer_server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build --if-present

  build_explorer_ui:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./explorer-ui
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - run: npm ci
        - run: npm run build --if-present

  build_runner_executor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./runner/executor
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build --if-present